### ISSUE TITLE
Custom SSL Certificate

### ISSUE THREAD

**Issue by alloylab** [skavanagh/KeyBox#121]
I tried falling these instructions, http://wiki.eclipse.org/Jetty/Howto/Configure_SSL, from the README however I am running into an issue when I try to add a Cert/Key pair to the keystore... I don't know what the default password is for the keystore (/opt/KeyBox-jetty/jetty/etc/keystore). Any Advice on how to proceed? Thanks.

This is command I am running to add my cert/key pair, keytool -importkeystore -srckeystore /ssl/jetty.pkcs12 -srcstoretype PKCS12 -destkeystore /opt/KeyBox-jetty/jetty/etc/keystore;

**Comment by alloylab** [comment]
Solved.

**Comment by TheGrandPackard** [comment]
For anyone else skimming these issues to get custom SSL certificates working, I ran into this problem as well. I ended up deleting the keystore and starting with a fresh one since it was not the default 'changeit' password. Also, for more information on adding a custom cert check out this other issue: #130
