### ISSUE TITLE
Console does not display properly

### ISSUE THREAD

**Issue by liwenbin1991** [skavanagh/KeyBox#132]
I use eclipse to open the project, running in the jetty. 

![image](https://cloud.githubusercontent.com/assets/7207820/13946455/b018aa24-f04f-11e5-89df-a3b078722a88.png)

**Comment by skavanagh** [comment]
That happens is happens when websockets are being blocked / disabled

I've had ppl have issues/fixes with nginx proxy. https://github.com/skavanagh/KeyBox/issues/51

You could also be using an older browser. I'd make sure you are on the latest version and you can test your browser for support here.
http://websocketstest.com/

**Comment by liwenbin1991** [comment]
Thank you for reminding.
I use eclipse jetty plug-in startup, so in the “Run Configurations -- > "Options" tick "Enable Websocket Support".
