### ISSUE TITLE
reset admin pwd when otp is activated

### ISSUE THREAD

**Issue by kramer2** [skavanagh/KeyBox#176]
file keybox.h2.db is not exist. how to reset admin password ? I have OTP switched on (codes generated on Android phone)

**Comment by skavanagh** [comment]
The DB is in the jetty/keybox/WEB-INF/classes/keydb directory and is usually called either keybox.h2.db or keybox.mv.db.  OTP can be turned off in the KeyBoxConfig.properties.  Another "Full access" user can reset the password. Otherwise you will have to write something to update the password in the DB (which could be difficult)

**Comment by michalsiu** [comment]
Can a user with "full access" reset the admin password without knowledge of the current one?

I have the admin password stored in a password vault and joined with Google Authenticator, but cannot login for some reason (could previously). I wanted to change the password, but KeyBox claims that the string I put in is invalid.
Any help would be much appreciated (I really don't want to start all over again :( )
