### ISSUE TITLE
passphrase of custom generated keypair should not be forgotten

### ISSUE THREAD

**Issue by willgopublic** [skavanagh/KeyBox#246]
Hello, thanks for your program.

I have created my own keypair with a passphrase.
I have put the paths to the files and the passphrase in the config-file.
I have restarted the application and the application has replaced the values for resetApplicationSSHKey and defaultSSHPassphrase to false & ${randomPassPhrase} .
Now when a user adds a new key to their profile, keybox seems to be unable to insert it into the .authorized_keys and when going to the system account I see that for that system the status is no longer 'Success' but rather 'Passphrase Authentication Failed'.

This could be an unexpected feature (requiring a sysadmin to approve the addition of a key) or a bug (a key should be added to a system that a user has been granted access to).

Another option is of course that I am doing something wrong.

I hope someone can shed some light on this.

**Comment by skavanagh** [comment]
Everything seems to be correct with this.

> I have restarted the application and the application has replaced the values for resetApplicationSSHKey and defaultSSHPassphrase to false & ${randomPassPhrase} .

This is the correct behavior.  The resetApplicationSSHKey property is set back to false, since we don't want the key to be reset on the next startup of the server.  And defaultSSHPassphrase is set back to the default, since the passphrase is encrypted and stored in the DB (and it shouldn't remain cleartext in a properties file).  The key itself can actually be removed from the system.

https://github.com/skavanagh/KeyBox#supplying-a-custom-ssh-key-pair

> Now when a user adds a new key to their profile, keybox seems to be unable to insert it into the .authorized_keys and when going to the system account I see that for that system the status is no longer 'Success' but rather 'Passphrase Authentication Failed'.

This would happen if the passphrase wasn't registered correctly.  It appears to be working, as long as the property values are set correctly. 

When you register a custom key make sure you have these values set.
```
resetApplicationSSHKey=true
privateKey=<path>/<newkey>
publicKey=<path>/<newkey>.pub
defaultSSHPassphrase=<newkey passhrase>
```
Then go to the Manage -> Systems screen and refresh the systems.

**Comment by willgopublic** [comment]
Okay, I might investigate further at some later moment. Thank you for the reply, I will close this issue.
