### ISSUE TITLE
Using SSH Client to connect via Keybox to be able to use SCP

### ISSUE THREAD

**Issue by phal0r** [skavanagh/KeyBox#247]
Hi @skavanagh,

thanks for your work on this great tool. We are currently evaluating if we could use this for server management. One requirement is to use SCP (or SSH Tunneling) that the ssh client provides.

I did not find a way how to accomplish this. Is this generally discouraged or did I jut not find the right spot to look at? 

Thanks in advance for your help!

**Comment by skavanagh** [comment]
It goes: Client - HTTP -> KeyBox - SSH -> Target Server.

Files can be uploaded and copied to the target servers. The client uploads to KeyBox over HTTP(s) and KeyBox copies to the target servers with SCP. Files cannot be copied from the target server to the client (it's discouraged and there isn't anything written to allow it).  SSH Tunneling is impossible since the client is connecting first through HTTP.

**Comment by phal0r** [comment]
Hi @skavanagh ,

thank you very much for the clarification (and sorry for the late response).
